trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

  variable:
    name: ResourceGroupName+
    value: 'rg-mazneu-cor-a-sandbox-espinalg-001'
stages:

- stage: Lint
  jobs: 
  - template: pipeline-templates/lint.yml

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Test

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Production