trigger:
  branches:
    include:
      - main  # Cambia esto según la rama desde la que quieras que se ejecute el pipeline

variables:
- name: ServiceConnectionName
  value: cor-sandbox-espinalg-001
- name: ResourceGroupName
  value: rg-mazneu-cor-a-sandbox-espinalg-001
- name: AzureRegion
  value: westus3
- name: parametersFile
  value: 'parameters-main.json'
- name: bicepFile
  value: main.bicep

pool:
  vmImage: ubuntu-latest

stages:

- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file $(bicepFile)
        name: LintBicepCode
        displayName: Run Bicep linter

- stage: Publish
  jobs:
  - job: Publish
    steps:
      - task: AzureCLI@2
        name: Publish
        displayName: Publish template spec
        inputs:
          azureSubscription: $(ServiceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage account create \
              --resource-group $(ResourceGroupName) \
              --version $(Build.BuildNumber) \
              --template-file $(bicepFile) \
              --parameters-file $(parametersFile) \
